services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      PORT: 3000
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "3000:3000"
    command: >-
      sh -c "until npx prisma migrate deploy; do echo 'waiting for db...'; sleep 2; done; npm start"

  frontend:
    build:
      context: ./frontend
      args:
        # Build the client bundle to call the host-exposed backend
        VITE_API_URL: http://localhost:3000
    environment:
      PORT: 5173
    ports:
      - "5173:5173"
