services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    command: >-
      sh -c "until npx prisma migrate deploy; do echo 'waiting for db...'; sleep 2; done; npm start"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
